export const DEV_SIGNUP_REQUEST = 'DEV_SIGNUP_REQUEST';
export const DEV_SIGNUP_SUCCESS = 'DEV_SIGNUP_SUCCESS';
export const DEV_SIGNUP_FAIL = 'DEV_SIGNUP_FAIL';

export const DEV_SIGNIN_REQUEST = 'DEV_SIGNIN_REQUEST';
export const DEV_SIGNIN_SUCCESS = 'DEV_SIGNIN_SUCCESS';
export const DEV_SIGNIN_FAIL = 'DEV_SIGNIN_FAIL';

export const DEV_SIGNOUT = 'DEV_SIGNOUT';
