export const DEV_SIGNUP_REQUEST = 'DEV_SIGNUP_REQUEST';
export const DEV_SIGNUP_SUCCESS = 'DEV_SIGNUP_SUCCESS';
export const DEV_SIGNUP_FAIL = 'DEV_SIGNUP_FAIL';

export const DEV_SIGNIN_REQUEST = 'DEV_SIGNIN_REQUEST';
export const DEV_SIGNIN_SUCCESS = 'DEV_SIGNIN_SUCCESS';
export const DEV_SIGNIN_FAIL = 'DEV_SIGNIN_FAIL';
export const DEV_SIGNOUT = 'DEV_SIGNOUT';

export const GET_DEV_PROFILE_REQUEST = 'GET_DEV_PROFILE_REQUEST';
export const GET_DEV_PROFILE_SUCCESS = 'GET_DEV_PROFILE_SUCCESS';
export const GET_DEV_PROFILE_FAIL = 'GET_DEV_PROFILE_FAIL';
export const GET_DEV_PROFILE_RESET = 'GET_DEV_PROFILE_RESET';

export const DEV_PROFILE_DELETE_REQUEST = 'DEV_PROFILE_DELETE_REQUEST';
export const DEV_PROFILE_DELETE_SUCCESS = 'DEV_PROFILE_DELETE_SUCCESS';
export const DEV_PROFILE_DELETE_FAIL = 'DEV_PROFILE_DELETE_FAIL';
export const DEV_PROFILE_DELETE_RESET = 'DEV_PROFILE_DELETE_RESET';

export const DEV_PROFILE_EDIT_REQUEST = 'DEV_PROFILE_EDIT_REQUEST';
export const DEV_PROFILE_EDIT_SUCCESS = 'DEV_PROFILE_EDIT_SUCCESS';
export const DEV_PROFILE_EDIT_FAIL = 'DEV_PROFILE_EDIT_FAIL';
export const DEV_PROFILE_EDIT_RESET = 'DEV_PROFILE_EDIT_RESET';

export const DEV_DP_EDIT_REQUEST = 'DEV_DP_EDIT_REQUEST';
export const DEV_DP_EDIT_SUCCESS = 'DEV_DP_EDIT_SUCCESS';
export const DEV_DP_EDIT_FAIL = 'DEV_DP_EDIT_FAIL';
export const DEV_DP_EDIT_RESET = 'DEV_DP_EDIT_RESET';

export const DEV_COVER_EDIT_REQUEST = 'DEV_COVER_EDIT_REQUEST';
export const DEV_COVER_EDIT_SUCCESS = 'DEV_COVER_EDIT_SUCCESS';
export const DEV_COVER_EDIT_FAIL = 'DEV_COVER_EDIT_FAIL';
export const DEV_COVER_EDIT_RESET = 'DEV_COVER_EDIT_RESET';

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_RESET = 'CREATE_ARTICLE_RESET';

export const FETCH_ALL_ARTICLE_REQUEST = 'FETCH_ALL_ARTICLE_REQUEST';
export const FETCH_ALL_ARTICLE_SUCCESS = 'FETCH_ALL_ARTICLE_SUCCESS';
export const FETCH_ALL_ARTICLE_FAIL = 'FETCH_ALL_ARTICLE_FAIL';

export const FETCH_SINGLE_ARTICLE_REQUEST = 'FETCH_SINGLE_ARTICLE_REQUEST';
export const FETCH_SINGLE_ARTICLE_SUCCESS = 'FETCH_SINGLE_ARTICLE_SUCCESS';
export const FETCH_SINGLE_ARTICLE_FAIL = 'FETCH_SINGLE_ARTICLE_FAIL';

export const FETCH_USER_ARTICLES_REQUEST = 'FETCH_USER_ARTICLES_REQUEST';
export const FETCH_USER_ARTICLES_SUCCESS = 'FETCH_USER_ARTICLES_SUCCESS';
export const FETCH_USER_ARTICLES_FAIL = 'FETCH_USER_ARTICLES_FAIL';

export const DELETE_SINGLE_ARTICLE_REQUEST = 'DELETE_SINGLE_ARTICLE_REQUEST';
export const DELETE_SINGLE_ARTICLE_SUCCESS = 'DELETE_SINGLE_ARTICLE_SUCCESS';
export const DELETE_SINGLE_ARTICLE_FAIL = 'DELETE_SINGLE_ARTICLE_FAIL';
export const DELETE_SINGLE_ARTICLE_RESET = 'DELETE_SINGLE_ARTICLE_RESET';

export const ARTICLE_EDIT_REQUEST = 'ARTICLE_EDIT_REQUEST';
export const ARTICLE_EDIT_SUCCESS = 'ARTICLE_EDIT_SUCCESS';
export const ARTICLE_EDIT_FAIL = 'ARTICLE_EDIT_FAIL';
export const ARTICLE_EDIT_RESET = 'ARTICLE_EDIT_RESET';

export const DEV_PUBLIC_VIEW_REQUEST = 'DEV_PUBLIC_VIEW_REQUEST';
export const DEV_PUBLIC_VIEW_SUCCESS = 'DEV_PUBLIC_VIEW_SUCCESS';
export const DEV_PUBLIC_VIEW_FAIL = 'DEV_PUBLIC_VIEW_FAIL';
export const DEV_PUBLIC_VIEW_RESET = 'DEV_PUBLIC_VIEW_RESET';

export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS';
export const UPVOTE_fDETAILS_SUCCESS = 'UPVOTE_fDETAILS_SUCCESS';
export const UPVOTE_fUSERPROFILE_SUCCESS = 'UPVOTE_fUSERPROFILE_SUCCESS';
export const UPVOTE_FAIL = 'UPVOTE_FAIL';

export const DOWNVOTE_SUCCESS = 'DOWNVOTE_SUCCESS';
export const DOWNVOTE_fDETAILS_SUCCESS = 'DOWNVOTE_fDETAILS_SUCCESS';
export const DOWNVOTE_fUSERPROFILE_SUCCESS = 'DOWNVOTE_fUSERPROFILE_SUCCESS';
export const DOWNVOTE_FAIL = 'DOWNVOTE_FAIL';

export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAIL = 'FETCH_COMMENT_FAIL';
export const ADD_COMMENT = 'ADD_COMMENT';

export const SHARE_ARTICLE_REQUEST = 'SHARE_ARTICLE_REQUEST';
export const SHARE_ARTICLE_SUCCESS = 'SHARE_ARTICLE_SUCCESS';
export const SHARE_ARTICLE_FAILED = 'SHARE_ARTICLE_FAILED';

export const GET_SHARED_ARTICLE_REQUEST = 'GET_SHARED_ARTICLE_REQUEST';
export const GET_SHARED_ARTICLE_SUCCESS = 'GET_SHARED_ARTICLE_SUCCESS';
export const GET_SHARED_ARTICLE_FAILED = 'GET_SHARED_ARTICLE_FAILED';

export const DELETE_SHARED_ARTICLE_REQUEST = 'DELETE_SHARED_ARTICLE_REQUEST';
export const DELETE_SHARED_ARTICLE_SUCCESS = 'DELETE_SHARED_ARTICLE_SUCCESS';
export const DELETE_SHARED_ARTICLE_FALIED = 'DELETE_SHARED_ARTICLE_FALIED';

export const GET_ALL_QUESTIONS_REQUEST = 'GET_ALL_QUESTIONS_REQUEST';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_FAILED = 'GET_ALL_QUESTIONS_FAILED';

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILED = 'CREATE_QUESTION_FAILED';
export const CREATE_QUESTION_RESET = 'CREATE_QUESTION_RESET';

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST';
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS';
export const QUESTION_DELETE_FAILED = 'QUESTION_DELETE_FAILED';
export const QUESTION_DELETE_RESET = 'QUESTION_DELETE_RESET';

export const QUESTION_EDIT_REQUEST = 'QUESTION_EDIT_REQUEST';
export const QUESTION_EDIT_SUCCESS = 'QUESTION_EDIT_SUCCESS';
export const QUESTION_EDIT_FAILED = 'QUESTION_EDIT_FAILED';
export const QUESTION_EDIT_RESET = 'QUESTION_EDIT_RESET';

export const GET_Q_ANSWERS_REQUEST = 'GET_Q_ANSWERS_REQUEST';
export const GET_Q_ANSWERS_SUCCESS = 'GET_Q_ANSWERS_SUCCESS';
export const ADD_ANSWER = 'ADD_ANSWER';
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const GET_Q_ANSWERS_FAILED = 'GET_Q_ANSWERS_FAILED';

export const UPVOTE_ANSWER_SUCCESS = 'UPVOTE_ANSWER_SUCCESS';
export const UPVOTE_ANSWER_FAIL = 'UPVOTE_ANSWER_FAIL';

export const DOWNVOTE_ANSWER_SUCCESS = 'DOWNVOTE_ANSWER_SUCCESS';
export const DOWNVOTE_ANSWER_FAIL = 'DOWNVOTE_ANSWER_FAIL';

export const GET_USER_QUESTIONS_REQUEST = 'GET_USER_QUESTIONS_REQUEST';
export const GET_USER_QUESTIONS_SUCCESS = 'GET_USER_QUESTIONS_SUCCESS';
export const GET_USER_QUESTIONS_FAILED = 'GET_USER_QUESTIONS_FAILED';
